---
title: "Saplings@Ecology　2022勉強会"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# データ出典元＆クレジット　Data source & Credits

### 多様性データ

- 該当データ
  - **data/Community_data.csv（プロット内の出現種のデータ）**
  - **data/Island_data.csv（島の詳細データ）**
  - **data/Plant_functional_trait_data.csv（植物の機能的特性データ）**
  - **data/Species_data.csv（種名リスト）**
  - **data/Plant_occeurences.csv（GBIF上の観察記録）**

- 出典元

  > Schrader, J., Moeljono, S., Tambing, J., Sattler, C., & Kreft, H. 2020. A new dataset on plant occurrences on small islands, including species abundances and functional traits across different spatial scales. Biodiversity Data Journal 8:.
  > 
  > URL: https://bdj.pensoft.net/article/55275/instance/5664007/
  > 
  > Use license: Creative Commons Public Domain Waiver (CC-Zero)

- 備考
  - 上記で提供されているデータをRで読み込める形に編集し、CSV形式で保存した。


### ベースマップデータ

- 該当データ
  - **data/basemap_osm.geojson**

- 出典元

  > Land polygons
  > 
  > Polygons for all land areas in the world, ie. continents and islands. Optionally, large polygons are split into smaller overlapping chunks that are easier and faster to work with.
  > 
  > © OpenStreetMap contributors
  >
  > URL:https://osmdata.openstreetmap.de/data/land-polygons.html

- 備考
  - 上記で提供されているデータの一部を抜き出し、GeoJSON形式で保存した。

